---
- homebrew: name=awscli state=present
- homebrew: name=bats state=present
- homebrew: name=boot2docker state=present
- homebrew: name=cmake state=present
- homebrew: name=docker state=present
- homebrew: name=docker-compose state=present
- homebrew: name=gist state=present
- homebrew: name=git state=present
- homebrew: name=hub state=present
- homebrew: name=jenv state=present
- homebrew: name=jq state=present
- homebrew: name=maven state=present
- homebrew: name=node state=present
- homebrew: name=ruby state=present
- homebrew: name=rust state=present
- homebrew: name=sbt state=present
- homebrew: name=scala state=present
- homebrew: name=xmlstarlet state=present
- homebrew_cask: name=cyberduck state=present
- homebrew_cask: name=cornerstone state=present
- homebrew_cask: name=intellij-idea-ce state=present
- homebrew_cask: name=java state=present
- homebrew_cask: name=java6 state=present
- homebrew_cask: name=java7 state=present
- homebrew_cask: name=slack state=present
- homebrew_cask: name=sourcetree state=present
- homebrew_cask: name=vagrant state=present
- homebrew_cask: name=virtualbox state=present
