---
- hosts: localhost
  tasks:
    - homebrew_tap: tap=homebrew/dupes,homebrew/completions,homebrew/versions state=present
    - homebrew_tap: tap=caskroom/cask,caskroom/fonts,caskroom/versions state=present
    - homebrew: update_homebrew=yes upgrade_all=yes
    - homebrew: name=cmake state=latest
    - homebrew: name=htop-osx state=latest
    - homebrew_cask: name=alfred state=present
