---
- hosts: localhost
  vars:
      is_bbc: false
  roles:
    - common
    - workstation
    - dev
    - creativity
    - {
        "role": "gaming",
        "when": "not is_bbc"
      }
    - {
        "role": "bbc",
        "when": "is_bbc"
      }
