---

# Homebrew dependencies
workstation_homebrew_dependencies:
  - tomcat
  - redis
  - mongodb


# Homebrew Cask dependencies
workstation_homebrew_cask_dependencies:
  - 1password
  - alfred
  - atom
  - bartender
  - caffeine
  - chromecast
  - cinch
  - dropbox
  - evernote
  - flux
  - google-chrome
  - google-drive
  - iterm2
  - keka
  - lunchy
  - music-manager
  - plug
  - radiant-player
  - skype
  - sonos
  - totalfinder
  - vlc


# Defaults that require Finder to be restarted
osx_defaults_finder_values:

  # Show hidden files in Finder
  - {
      "domain": "com.apple.finder",
      "key": "AppleShowAllFiles",
      "type": "boolean",
      "value": true,
      "state": "present"
    }


# Defaults that require the UI Server to be restarted
osx_defaults_system_ui_server_values:

  # Disable natural scroll direction
  - {
      "domain"  : "NSGlobalDomain",
      "key"     : "com.apple.swipescrolldirection",
      "type"    : "boolean",
      "value"   : false,
      "state"   : "present"
    }

  # Use Dark theme in Yosemite
  - {
      "domain": "NSGlobalDomain",
      "key": "AppleInterfaceStyle",
      "type": "string",
      "value": "Dark",
      "state": "absent"
    }

  # Add a context menu item for showing web inspector in web views
  - {
      "domain": "NSGlobalDomain",
      "key": "WebKitDeveloperExtras",
      "type": "boolean",
      "value": true,
      "state": "present"
    }

  # Don't display dashboard as a space pre-Yosemite
  - {
      "domain"  : "com.apple.dock",
      "key"     : "dashboard-in-overlay",
      "type"    : "boolean",
      "value"   : true,
      "state"   : "present"
    }

  # Auto hide the dock
  - {
      "domain"  : "com.apple.dock",
      "key"     : "autohide",
      "type"    : "boolean",
      "value"   : true,
      "state"   : "present"
    }


# Defaults that require no further action
osx_defaults_values:

  # Check for updates daily
  - {
      "domain": "com.apple.SoftwareUpdate",
      "key": "ScheduleFrequency",
      "type": "integer",
      "value": 1,
      "state": "present"
    }
